//import React from 'react';

function App() {
  return (
    <div style={{ textAlign: 'center', marginTop: '50px' }}>
      <h1>Hello, World!</h1>
      <h1>Hello, World!</h1>
      <h1>Hello, World!</h1>
      <h1>Hello, World!</h1>
      <h1>Hello, World!</h1>
      <h1>Hello, World!</h1>
      <h1>Hello, World!</h1>
      <h1>Hello, World!</h1>
      <h1>Hello, World!</h1>
      <h1>Hello, World!</h1>
      <h1>Hello, World!</h1>
      <h1>Hello, World!</h1>
      <h1>Hello, World!</h1>
      <h1>Hello, World!</h1>
      <h1>Hello, World!</h1>
      <h1>Hello, World!</h1>
      <h1>Hello, World!</h1>
      <h1>Hello, World!</h1>
      <h1>Hello, World!</h1>
      <h1>Hello, World!</h1>
      <h1>Hello, World!</h1>
      <h1>Hello, World!</h1>
      <h1>Hello, World!</h1>
      <h1>Hello, World!</h1>
      <h1>Hello, World!</h1>
      <h1>Hello, World!</h1>
      <h1>Hello, World!</h1>
      <h1>Hello, World!</h1>
      <h1>Hello, World!</h1>
      <h1>Hello, World!</h1>
      <h1>Hello, World!</h1>
      <h1>Hello, World!</h1>
      <h1>Hello, World!</h1>
      <h1>Hello, World!</h1>
      <h1>Hello, World!</h1>
      <h1>Hello, World!</h1>
      <h1>Hello, World!</h1>
      <h1>Hello, World!</h1>
      <h1>Hello, World!</h1>
      <h1>Hello, World!</h1>
      <h1>Hello, World!</h1>
      <h1>Hello, World!</h1>
      <h1>Hello, World!</h1>
      <h1>Hello, World!</h1>
      <h1>Hello, World!</h1>
      <h1>Hello, World!</h1>
      <h1>Hello, World!</h1>
      <h1>Hello, World!</h1>
      <h1>Hello, World!</h1>
      <h1>Hello, World!</h1>
      <h1>Hello, World!</h1>
      <h1>Hello, World!</h1>
      <h1>Hello, World!</h1>
      <h1>Hello, World!</h1>
      <h1>Hello, World!</h1>
      <h1>Hello, World!</h1>
      <h1>Hello, World!</h1>
      <h1>Hello, World!</h1>
      <h1>Hello, World!</h1>
      <h1>Hello, World!</h1>
      <h1>Hello, World!</h1>
      <h1>Hello, World!</h1>
      <h1>Hello, World!</h1>
      <h1>Hello, World!</h1>
      <h1>Hello, World!</h1>
      <h1>Hello, World!</h1>
      <h1>Hello, World!</h1>
      <h1>Hello, World!</h1>
      <h1>Hello, World!</h1>
      <h1>Hello, World!</h1>
      <h1>Hello, World!</h1>
      <h1>Hello, World!</h1>
      <h1>Hello, World!</h1>
      <h1>Hello, World!</h1>
      <h1>Hello, World!</h1>
      <h1>Hello, World!</h1>
      <h1>Hello, World!</h1>
      <h1>Hello, World!</h1>
      <h1>Hello, World!</h1>
      <h1>Hello, World!</h1>
      <h1>Hello, World!</h1>
      <h1>Hello, World!</h1>
      <h1>Hello, World!</h1>
      <h1>Hello, World!</h1>
      <h1>Hello, World!</h1>
      <h1>Hello, World!</h1>
      <h1>Hello, World!</h1>
      <h1>Hello, World!</h1>
      <h1>Hello, World!</h1>
      <h1>Hello, World!</h1>
      <h1>Hello, World!</h1>
      <h1>Hello, World!</h1>
      <h1>Hello, World!</h1>
      <h1>Hello, World!</h1>
      <h1>Hello, World!</h1>
      <h1>Hello, World!</h1>
      <h1>Hello, World!</h1>
      <h1>Hello, World!</h1>
      <h1>Hello, World!</h1>
      <h1>Hello, World!</h1>
      <h1>Hello, World!</h1>
      <h1>Hello, World!</h1>
      <h1>Hello, World!</h1>
      <h1>Hello, World!</h1>
      <h1>Hello, World!</h1>
      <h1>Hello, World!</h1>
      <h1>Hello, World!</h1>
      <h1>Hello, World!</h1>
      <h1>Hello, World!</h1>
      <h1>Hello, World!</h1>
      <h1>Hello, World!</h1>
      <h1>Hello, World!</h1>
      <h1>Hello, World!</h1>
      <h1>Hello, World!</h1>
      <h1>Hello, World!</h1>
      <h1>Hello, World!</h1>
      <h1>Hello, World!</h1>
      <h1>Hello, World!</h1>
      <h1>Hello, World!</h1>
      <h1>Hello, World!</h1>
      <h1>Hello, World!</h1>
      <h1>Hello, World!</h1>
      <h1>Hello, World!</h1>
      <h1>Hello, World!</h1>
      <h1>Hello, World!</h1>
      <h1>Hello, World!</h1>
      <h1>Hello, World!</h1>
      <h1>Hello, World!</h1>
      <h1>Hello, World!</h1>
      <h1>Hello, World!</h1>
      <h1>Hello, World!</h1>
      <p>Welcome to the LootFinder project.</p>
    </div>
  );
}

export default App;